/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JSplitPane;

/**
 *
 * @author Swapnil
 */
public class CustomerHotelJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    EcoSystem ecosystem;
    DefaultTableModel model1;
    private UserAccount userAccount;
    DefaultTableModel model;
    Customer cust;
    JSplitPane screen;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public CustomerHotelJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, JSplitPane screen) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.screen = screen;
        this.userAccount = account;
        ecosystem = system;
        model = new DefaultTableModel();
        model1 = new DefaultTableModel();
        restListTable.setModel(model);
        orderTable.setModel(model1);
        cust = findCustomer();
        model.addColumn("Name");
        model.addColumn("Location");
        model.addColumn("Phone No");
        model1.addColumn("Id");
        model1.addColumn("Status");
        model1.addColumn("Restaurant");
        model1.addColumn("Delivery");
        model1.addColumn("FeedBack");
        model1.addColumn("Comment");
        populateRequestTable();
        populateCustomerOrders();
        
    }

    public Customer findCustomer() {
        for (int i = 0; i < ecosystem.getCustomerDirectory().getCustomerList().size(); i++) {
            if (ecosystem.getCustomerDirectory().getCustomerList().get(i).getAccountDetails().getUsername().equals(this.userAccount.getUsername())) {
                return ecosystem.getCustomerDirectory().getCustomerList().get(i);
            }
        }
        return null;
    }

    public void populateCustomerCart() {
        Customer cust = findCustomer();
        for (int i = model1.getRowCount() - 1; i >= 0; i--) {
            model1.removeRow(i);
        }
        if (cust.gethotelorderList().size() > 0) {
            for (int i = 0; i < cust.gethotelorderList().size(); i++) {
                model1.addRow(new Object[]{
                    cust.gethotelorderList().get(i).getItem(),
                    cust.gethotelorderList().get(i).getPrice(),
                    cust.gethotelorderList().get(i).getQuantity(),});
            }
        }
    }

    public void populateCustomerOrders() {
        for (int i = model1.getRowCount() - 1; i >= 0; i--) {
            model1.removeRow(i);
        }
        for (int i = 0; i < cust.getHotelorderDirectoryList().size(); i++) {
            System.out.println(cust.getHotelorderDirectoryList().get(i).getId());
            model1.addRow(new Object[]{
                i+1,
                cust.getHotelorderDirectoryList().get(i).getStatus(),
                cust.getHotelorderDirectoryList().get(i).getRestaurant().getName(),
                cust.getHotelorderDirectoryList().get(i).getDeliveryMan().getName(),
                cust.getHotelorderDirectoryList().get(i).getFeedbackComment(),
                cust.getHotelorderDirectoryList().get(i).getComment()
            });
        }

    }

    public void populateRequestTable() {
        for (int i = 0; i < ecosystem.getHotel_Directory().getHotelList().size(); i++) {
            if( ecosystem.getHotel_Directory().getHotelList().get(i).getNetwork().equals(cust.getNetwork())){
            model.addRow(new Object[]{
                ecosystem.getHotel_Directory().getHotelList().get(i).getName(),
                ecosystem.getHotel_Directory().getHotelList().get(i).getLocation(),
                ecosystem.getHotel_Directory().getHotelList().get(i).getPhone(),});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        restListTable = new javax.swing.JTable();
        SelectRestBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        FeedbackTxt = new javax.swing.JTextField();
        FeedbackBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 108, 103));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        restListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Phone No", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(restListTable);
        if (restListTable.getColumnModel().getColumnCount() > 0) {
            restListTable.getColumnModel().getColumn(0).setResizable(false);
            restListTable.getColumnModel().getColumn(1).setResizable(false);
            restListTable.getColumnModel().getColumn(2).setResizable(false);
            restListTable.getColumnModel().getColumn(3).setResizable(false);
        }

        SelectRestBtn.setBackground(new java.awt.Color(127, 195, 126));
        SelectRestBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        SelectRestBtn.setText("Select Restaurant");
        SelectRestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectRestBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Select a Restaurant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(SelectRestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectRestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, 260));

        jPanel2.setBackground(new java.awt.Color(254, 254, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Status", "Restaurant Name", "Delivery Name", "Comment", "FeedBack"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(2).setResizable(false);
            orderTable.getColumnModel().getColumn(3).setResizable(false);
        }

        FeedbackTxt.setForeground(new java.awt.Color(72, 72, 72));
        FeedbackTxt.setToolTipText("");

        FeedbackBtn.setBackground(new java.awt.Color(127, 195, 126));
        FeedbackBtn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        FeedbackBtn.setText("Feedback");
        FeedbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Past Orders");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FeedbackTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FeedbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FeedbackTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FeedbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 580, 280));

        jLabel1.setBackground(new java.awt.Color(0, 108, 103));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restaurant_1.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 480, 270));

        title2.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        title2.setForeground(new java.awt.Color(254, 254, 226));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Restaurant Orders");
        add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 940, 60));

        jLabel3.setBackground(new java.awt.Color(0, 108, 103));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restaurant.gif"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void SelectRestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectRestBtnActionPerformed

        if (restListTable.getSelectedRow() >= 0) {
            CustomerOrderHotelJPanel mm = new CustomerOrderHotelJPanel(userProcessContainer, this.userAccount, ecosystem, ecosystem.getHotel_Directory().getHotelList().get(restListTable.getSelectedRow()), screen);
//            userProcessContainer.add("manageNetworkJPanel", mm);
//            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//            layout.next(userProcessContainer);
               screen.setRightComponent(mm);
        System.out.println("Restaurant Selected");
        } else {
            JOptionPane.showMessageDialog(this, "Please select a restaurant","Error message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SelectRestBtnActionPerformed

    private void FeedbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a order from table","Error message", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(!"Delivered".equals(cust.getHotelorderDirectoryList().get(selectedRow).getStatus())){
            JOptionPane.showMessageDialog(this, "Selected Order Not Delivered Yet","Error message", JOptionPane.ERROR_MESSAGE);
            return;
    }else{
            if(FeedbackTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Feedback cannot be empty","Error message", JOptionPane.ERROR_MESSAGE);
            return;
            }
            cust.getHotelorderDirectoryList().get(selectedRow).setFeedbackComment(FeedbackTxt.getText());
            JOptionPane.showMessageDialog(this, "Feedback added Successfully");
            FeedbackTxt.setText("");
            populateCustomerOrders();
        }
    }//GEN-LAST:event_FeedbackBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FeedbackBtn;
    private javax.swing.JTextField FeedbackTxt;
    private javax.swing.JButton SelectRestBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable restListTable;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
